export const REMOVE_AUTH_INFO = 'AUTH_REMOVE_AUTH_INFO';

export const UPDATE_AUTH_INFO = 'AUTH_UPDATE_AUTH_INFO';

export const LOGIN_FAILED = 'AUTH_LOGIN_FAILED';

export const LOGIN_PROCESSING = 'AUTH_LOGIN_PROCESSING';